In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [7]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D
X = asarray([[1, 2],[3, 4]])
print(X)

[[1 2]
 [3 4]]


In [8]:
X = X.reshape((1,2,2,1))

In [9]:
model = Sequential()
model.add(UpSampling2D(input_shape=(2,2,1)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [10]:
yhat = model.predict(X)

In [11]:
yhat = yhat.reshape((4,4))
print(yhat)

[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


In [12]:
X = asarray([[1, 2],[3, 4]])
print(X)
X = X.reshape((1,2,2,1))
model_one = Sequential()
model_one.add(UpSampling2D(input_shape=(2,2,1),size=(2,3)))
model_one.summary()
yhat = model_one.predict(X)
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_2 (UpSampling2 (None, 4, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[[[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[1.]
   [1.]
   [1.]
   [2.]
   [2.]
   [2.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]

  [[3.]
   [3.]
   [3.]
   [4.]
   [4.]
   [4.]]]]


In [13]:
X = asarray([[1, 2],[3, 4]])
print(X)
X = X.reshape((1,2,2,1))
model_two = Sequential()
model_two.add(UpSampling2D(input_shape=(2,2,1),interpolation='bilinear'))
model_two.summary()
yhat = model_two.predict(X)
yhat = yhat.reshape((4,4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_3 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________
[[1.   1.25 1.75 2.  ]
 [1.5  1.75 2.25 2.5 ]
 [2.5  2.75 3.25 3.5 ]
 [3.   3.25 3.75 4.  ]]


In [14]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Reshape
from keras.layers import UpSampling2D
from keras.layers import Conv2D
model_three = Sequential()
model_three.add(Dense(128*5*5, input_dim=100))
model_three.add(Reshape((5,5,128)))

In [15]:
model_three.add(UpSampling2D())

In [16]:
model_three.add(Conv2D(1,(3,3), padding='same'))
model_three.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3200)              323200    
_________________________________________________________________
reshape (Reshape)            (None, 5, 5, 128)         0         
_________________________________________________________________
up_sampling2d_4 (UpSampling2 (None, 10, 10, 128)       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________


In [17]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import Conv2DTranspose
X = asarray([[1, 2],[3, 4]])
print(X)

[[1 2]
 [3 4]]


In [18]:
X = X.reshape((1,2,2,1))

In [19]:
model_four = Sequential()
model_four.add(Conv2DTranspose(1,(1,1), strides=(2,2), input_shape=(2,2,1)))
model_four.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose (Conv2DTran (None, 4, 4, 1)           2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [20]:
weights = [asarray([[[[1]]]]), asarray([0])]
model_four.set_weights(weights)

In [21]:
yhat = model_four.predict(X)

In [22]:
yhat = yhat.reshape((4, 4))
print(yhat)

[[1. 0. 2. 0.]
 [0. 0. 0. 0.]
 [3. 0. 4. 0.]
 [0. 0. 0. 0.]]


In [23]:
X = asarray([[1, 2],[3, 4]])
print(X)
X = X.reshape((1,2,2,1))
model_five = Sequential()
model_five.add(Conv2DTranspose(1,(3,3), strides=(2,2), padding='same', input_shape=(2,2,1)))
model_five.summary()
yhat = model_five.predict(X)
yhat = yhat.reshape((4, 4))
print(yhat)

[[1 2]
 [3 4]]
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_transpose_1 (Conv2DTr (None, 4, 4, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
[[-0.42777795  0.26507443 -1.1701136   0.53014886]
 [ 0.42138737  0.04272097  0.57254255  0.08544195]
 [-1.8491242   0.8119172  -4.166074    1.0936855 ]
 [ 1.2641621   0.12816292  0.8748528   0.1708839 ]]


In [24]:
model_six = Sequential()
model_six.add(Dense(128*5*5, input_dim=100))
model_six.add(Reshape((5,5,128)))
model_six.add(Conv2DTranspose(1,(3,3), strides=(2,2), padding='same'))
model_six.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3200)              323200    
_________________________________________________________________
reshape_1 (Reshape)          (None, 5, 5, 128)         0         
_________________________________________________________________
conv2d_transpose_2 (Conv2DTr (None, 10, 10, 1)         1153      
Total params: 324,353
Trainable params: 324,353
Non-trainable params: 0
_________________________________________________________________
